amcl:
  ros__parameters:
    use_sim_time: true
    # ----- Frames -----
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    tf_broadcast: true
    transform_tolerance: 1.0

    # ----- Laser / Scan -----
    scan_topic: scan
    map_topic: map
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0
    laser_min_range: -1.0
    max_beams: 60

    # ----- Noise / Motion Model -----
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # ----- Beam Skipping -----
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    # ----- Particle Filter -----
    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 1
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    save_pose_rate: 0.5

    # ----- Likelihood Weights -----
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1

    # ----- Update thresholds -----
    update_min_d: 0.25
    update_min_a: 0.2

    # ----- Initial Pose Handling -----
    set_initial_pose: false
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    # ----- Introspection -----
    introspection_mode: "disabled"

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "$(find-pkg-share antbot_navigation)/maps/my_world.yaml"
    topic_name: "map"
    frame_id: "map"
    introspection_mode: "disabled"

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    introspection_mode: "disabled"

costmap_filter_info_server:
  ros__parameters:
    type: 1
    filter_info_topic: "costmap_filter_info"
    mask_topic: "filter_mask"
    base: 0.0
    multiplier: 0.25

bt_navigator:
  ros__parameters:
    use_sim_time: true
    always_reload_bt_xml: true   # ช่วยเวลาแก้ไฟล์ BT แล้วไม่ต้องรีสตาร์ทนาน
    bt_search_directories:
      - $(find-pkg-share antbot_navigation)/behavior_trees
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    filter_duration: 0.3
    introspection_mode: "disabled"

    # จะปล่อยสองบรรทัดนี้ไว้ก็ได้ หรือจะให้ launch เป็นตัวกำหนดก็ได้
    default_nav_to_pose_bt_xml: "$(find-pkg-share antbot_navigation)/behavior_trees/navigate_w_replanning_and_recovery_ackermann.xml"
    default_nav_through_poses_bt_xml: "$(find-pkg-share antbot_navigation)/behavior_trees/navigate_w_replanning_and_recovery_ackermann.xml"

    navigators: ['navigate_to_pose']
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
      enable_groot_monitoring: false
      groot_server_port: 1667

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    costmap_update_timeout: 0.3

    min_x_velocity_threshold: 0.02
    min_y_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.02

    failure_tolerance: 0.3
    odom_topic: "odom"
    odom_duration: 0.3

    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.25
      movement_time_allowance: 25.0

    # ถึงเป้าต้อง "หยุดนิ่งจริง"
    goal_checker:
      plugin: "nav2_controller::StoppedGoalChecker"
      xy_goal_tolerance: 0.45
      yaw_goal_tolerance: 0.35
      trans_stopped_velocity: 0.02
      rot_stopped_velocity: 0.18

    # --- Regulated Pure Pursuit (Ackermann) ---
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      use_fixed_curvature_lookahead: true
      curvature_lookahead_dist: 0.35
      # รถพวงมาลัยหมุนอยู่กับที่ไม่ได้
      use_rotate_to_heading: false
      allow_reversing: true     # ถ้ารถถอยได้จริงค่อยเปลี่ยนเป็น true

      # เร็วช่วงครูซ แต่ชะลอเข้าเป้า
      desired_linear_vel: 0.80
      min_approach_linear_velocity: 0.05
      use_approach_linear_velocity_scaling: true
      approach_velocity_scaling_dist: 1.2

      # มองล่วงหน้าให้เสถียร (สำคัญกับ Ackermann)
      lookahead_time: 1.0
      lookahead_dist: 0.70
      min_lookahead_dist: 0.50
      max_lookahead_dist: 1.20
      use_velocity_scaled_lookahead_dist: true

      # จำกัดอัตราเลี้ยวให้สอดคล้องกับรัศมีเลี้ยวจริง:
      # แนะนำตั้ง max_angular_vel ≈ desired_linear_vel / R_min (เผื่อ ×1.1 ได้)
      # ตัวอย่าง ถ้า R_min = 1.0 m และ v = 0.60 → 0.66 rad/s
      max_angular_vel: 0.70
      max_angular_accel: 2.0

      # ให้ RPP ชะลอเมื่อเสี่ยงชน
      use_collision_detection: true

      # อื่น ๆ
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.60
      regulated_linear_scaling_min_speed: 0.12
      transform_tolerance: 0.1

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 8.0     # Smac หนักกว่า Navfn, 5–10Hz กำลังดี
    costmap_update_timeout: 1.0
    introspection_mode: "disabled"

    planner_plugins: ['SmacHybrid']
    SmacHybrid:
      plugin: 'nav2_smac_planner::SmacPlannerHybrid'

      # --- ค่าหลักเพื่อ Ackermann ---
      motion_model_for_search: 'REEDS_SHEPP'   # 'DUBIN' = วิ่งหน้าอย่างเดียว, 'REEDS_SHEPP' = หน้า/ถอย
      minimum_turning_radius: 0.75        # <<< ใส่รัศมีเลี้ยวน้อยสุดของรถคุณ (เมตร)
      angle_quantization_bins: 48

      # --- เพิ่มความฉลาดตอนเข้าเทียบเป้า + เร็วขึ้น ---
      use_final_approach_orientation: true
      analytic_expansion: true
      analytic_expansion_max_length: 3.0  # 2–5 m ได้
      downsample_costmap: true
      downsampling_factor: 2
      allow_unknown: true
      tolerance: 0.75
      max_iterations: 200000 # เพิ่มถ้าเส้นทางไม่สมบูรณ์
      lookup_table_size: 40.0
      cost_travel_multiplier: 2.0


smoother_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: global_costmap/costmap_raw          # ← เพิ่ม
    footprint_topic: global_costmap/published_footprint # ← เพิ่ม
    robot_base_frame: base_footprint
    transform_tolerance: 0.1

    smoother_plugins: ["constrained_smoother"]
    constrained_smoother:
      plugin: "nav2_constrained_smoother/ConstrainedSmoother"
      minimum_turning_radius: 0.75   # <<< ให้เท่ากับ Smac
      w_curve: 30.0                 # บทลงโทษความโค้งสูง (เพิ่มถ้าโค้งแคบเกิน)
      keep_start_orientation: true
      keep_goal_orientation: true


behavior_server:
  ros__parameters:
    use_sim_time: true
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    enable_stamped_cmd_vel: false

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    introspection_mode: "disabled"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      footprint_padding: 0.03
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      # robot_radius: 0.22  # ใช้รัศมีแทน footprint
      footprint: "[ [0.91, 0.35], [0.91, -0.35], [-0.18, -0.35], [-0.18, 0.35] ]"
      footprint_padding: 0.03
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: /scan
          data_type: "LaserScan"
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: true
          marking: true
          inf_is_valid: false

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: false
        footprint_clearing_enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:
          topic: /intel_realsense_r200_depth/points  # ปรับให้ตรงกับหัวข้อจริง
          data_type: "PointCloud2"
          transport_type: "raw"  # raw / zlib / draco / zstd
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: true
          marking: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.5

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.10
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true

      always_send_full_costmap: true
      introspection_mode: "disabled"

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      footprint: "[ [0.91, 0.35], [0.91, -0.35], [-0.18, -0.35], [-0.18, 0.35] ]"
      footprint_padding: 0.03
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          data_type: "LaserScan"
          clearing: true
          marking: true
          inf_is_valid: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 1.10
        cost_scaling_factor: 1.0
