ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    two_d_mode: true
    publish_tf: true

    # ==== Frames ====
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    base_frame: base_footprint
    world_frame: odom

    # ==== Timing / Behavior ====
    frequency: 30.0
    sensor_timeout: 0.2
    transform_time_offset: 0.0
    transform_timeout: 0.2
    predict_to_current_time: true
    print_diagnostics: true
    debug: false

    # ============================
    # ODOM
    # ============================
    odom0: /tricycle_controller/odom
    odom0_queue_size: 50
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    # x y z | r p yaw | vx vy vz | vr vp vyaw | ax ay az
    odom0_config: [ true,  true,  false,
                    false, false, true,
                    true,  false, false,
                    false, false, true,
                    false, false, false ]

    odom0_pose_use_fixed_covariance: true
    odom0_pose_covariance: [
      0.02, 0.0,  0.0,   0.0,   0.0,   0.0,
      0.0,  0.02, 0.0,   0.0,   0.0,   0.0,
      0.0,  0.0,  1000.0,0.0,   0.0,   0.0,
      0.0,  0.0,  0.0,   1000.0,0.0,   0.0,
      0.0,  0.0,  0.0,   0.0,   1000.0,0.0,
      0.0,  0.0,  0.0,   0.0,   0.0,   0.05]

    odom0_twist_use_fixed_covariance: true
    odom0_twist_covariance: [
      0.05, 0.0,   0.0,   0.0,    0.0,    0.0,
      0.0,  1000.0,0.0,   0.0,    0.0,    0.0,
      0.0,  0.0,   1000.0,0.0,    0.0,    0.0,
      0.0,  0.0,   0.0,   1000.0, 0.0,    0.0,
      0.0,  0.0,   0.0,   0.0,    1000.0, 0.0,
      0.0,  0.0,   0.0,   0.0,    0.0,    0.10]

    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 5.0

    # ============================
    # IMU
    # ============================
    imu0: /imu
    imu0_queue_size: 50
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    imu0_config: [ false, false, false,
                   true,  true,  true,
                   false, false, false,
                   false, false, true,
                   false, false, false ]

    imu0_orientation_use_fixed_covariance: true
    imu0_orientation_covariance: [
      0.0025, 0.0,   0.0,
      0.0,    0.0025,0.0,
      0.0,    0.0,   0.01]

    imu0_angular_velocity_use_fixed_covariance: true
    imu0_angular_velocity_covariance: [
      0.01, 0.0,  0.0,
      0.0,  0.01, 0.0,
      0.0,  0.0,  0.02]

    imu0_linear_acceleration_use_fixed_covariance: true
    imu0_linear_acceleration_covariance: [
      1000.0, 0.0,    0.0,
      0.0,    1000.0, 0.0,
      0.0,    0.0,    1000.0]

    imu0_pose_rejection_threshold: 0.8
    imu0_twist_rejection_threshold: 0.8