scan_filter_chain:
  - name: shadows
    type: laser_filters/LaserScanShadowFilter
    params:
      min_angle: -3.14159
      max_angle:  3.14159
      neighbors: 1
      window: 1

  - name: range_clip
    type: laser_filters/LaserScanRangeFilter
    params:
      lower_threshold: 0.15
      upper_threshold: 7.8
      lower_replacement_value: 0.0
      upper_replacement_value: 0.0