controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_controller:
      type: tricycle_controller/TricycleController

tricycle_controller:
  ros__parameters:
    traction_joint_name: "front_wheel_joint"
    steering_joint_name: "steering_joint"

    wheel_radius: 0.08
    wheelbase: 0.5335 

    # Frame IDs
    base_frame_id: "base_link"
    odom_frame_id: "odom"

    # ❗️ห้าม publish TF เอง ให้ EKF เป็นคนทำ
    publish_odom: true
    publish_odom_tf: false

    open_loop: false
    cmd_vel_timeout: 500
