twist_mux:
  ros__parameters:
    # เลือก input ตาม priority (มากกว่า = สำคัญกว่า)
    topics:
      - name: keyboard
        topic: /keyboard/cmd_vel
        timeout: 0.6
        priority: 90
      - name: joy
        topic: /joy/cmd_vel
        timeout: 0.6
        priority: 70
      - name: nav
        topic: /nav/cmd_vel
        timeout: 1.0
        priority: 50
    locks: []
