<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="antbot">

  <!-- ===== Params ===== -->
  <!-- ยกฐานจากพื้นเพิ่ม เพื่อลดการลากพื้น -->
  <xacro:property name="base_clearance" value="0.03"/>  <!-- ~3 ซม. -->

  <xacro:property name="mesh_path"    value="package://antbot_description/meshes"/>
  <xacro:property name="wheel_radius" value="0.08"/>   <!-- 8 cm -->
  <xacro:property name="wheel_width"  value="0.06"/>   <!-- 6 cm -->

  <!-- ขนาดกล่องแทนฐาน -->
  <xacro:property name="base_size_x" value="0.55"/>
  <xacro:property name="base_size_y" value="0.42"/>
  <xacro:property name="base_size_z" value="0.10"/>

  <!-- มวลสมเหตุสมผล -->
  <xacro:property name="base_mass"   value="5.0"/>   <!-- ~12 kg -->
  <xacro:property name="wheel_mass"  value="1.00"/>  <!-- ~1 kg/ล้อ -->
  <xacro:property name="frame_mass"  value="0.10"/>
  <xacro:property name="pillar_mass" value="0.20"/>
  <xacro:property name="lidar_mass"  value="0.10"/>
  <xacro:property name="omron_mass"  value="0.10"/>
  <xacro:property name="steer_mass"  value="0.05"/>

  <!-- ===== Macros: inertia ให้ถูกฟิสิกส์ ===== -->
  <!-- กล่อง: ขยับจุดมวลให้ตรงกับ collision -->
  <xacro:macro name="inertial_box" params="mass x y z ox oy oz">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="${ox} ${oy} ${oz}"/>
      <inertia
        ixx="${mass*(y*y + z*z)/12.0}" ixy="0" ixz="0"
        iyy="${mass*(x*x + z*z)/12.0}" iyz="0"
        izz="${mass*(x*x + y*y)/12.0}"/>
    </inertial>
  </xacro:macro>

  <!-- ทรงกระบอกแกน X (ล้อหมุนรอบแกน X) -->
  <xacro:macro name="inertial_cyl_x" params="mass r l">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0"/>
      <!-- Ixx = 1/2 m r^2 ; Iyy=Izz = 1/12 m(3r^2 + l^2) -->
      <inertia
        ixx="${0.5*mass*r*r}" ixy="0" ixz="0"
        iyy="${mass*(3*r*r + l*l)/12.0}" iyz="0"
        izz="${mass*(3*r*r + l*l)/12.0}"/>
    </inertial>
  </xacro:macro>

  <!-- ===== Base ===== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}/antbot_base.stl"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>

    <!-- collision เป็นกล่อง และยกขึ้นครึ่งความหนา + ระยะเผื่อ -->
    <collision name="base_link_collision">
      <origin xyz="0 0 ${base_size_z/2.0 + base_clearance}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
      </geometry>
      <!-- ลด friction ของฐานเพื่อลดแรงต้านเมื่อเผลอแตะพื้น -->
      <surface>
        <friction>
          <ode>
            <mu>0.3</mu>
            <mu2>0.3</mu2>
          </ode>
        </friction>
      </surface>
    </collision>

    <!-- inertial ตรงกับ collision -->
    <xacro:inertial_box
      mass="${base_mass}"
      x="${base_size_x}"
      y="${base_size_y}"
      z="${base_size_z}"
      ox="0" oy="0" oz="${base_size_z/2.0 + base_clearance}"/>
  </link>

  <!-- ===== Rear Left Wheel ===== -->
  <link name="wheel_rear_left_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}/wheel_rear_centered_clean.stl"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>

    <!-- cylinder แกน X -->
    <collision name="wheel_rear_left_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.8</mu>
            <mu2>1.8</mu2>
          </ode>
        </friction>
        <!-- contact แข็งขึ้น ลดอาการเด้ง/ลื่น -->
        <contact>
          <ode>
            <kp>1e7</kp>
            <kd>1e5</kd>
          </ode>
        </contact>
      </surface>
    </collision>

    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="wheel_rear_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_rear_left_link"/>
    <origin xyz="0.285 0.5 ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <!-- ลดแดมป์ให้ล้อขึ้นรอบไว -->
    <dynamics damping="0.001" friction="0.0"/>
    <!-- เพิ่มเพดานแรง/ความเร็ว -->
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <!-- ===== Rear Right Wheel ===== -->
  <link name="wheel_rear_right_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}/wheel_rear_centered_clean.stl"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>

    <collision name="wheel_rear_right_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.8</mu>
            <mu2>1.8</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1e7</kp>
            <kd>1e5</kd>
          </ode>
        </contact>
      </surface>
    </collision>

    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="wheel_rear_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_rear_right_link"/>
    <origin xyz="-0.245 0.5 ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.001" friction="0.0"/>
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <!-- ===== Steering ===== -->
  <link name="steering_link">
    <inertial>
      <mass value="${steer_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="steering_joint" type="revolute">
    <parent link="base_link"/>
    <child  link="steering_link"/>
    <origin xyz="0.07 -0.04 ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- ลดแดมป์เพื่อให้เลี้ยวตอบสนองไวขึ้น -->
    <dynamics damping="0.05" friction="0.0"/>
    <limit effort="12.0" velocity="12.0" lower="-0.6" upper="0.6"/>
  </joint>

  <!-- ===== Front Wheel ===== -->
  <link name="wheel_front_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}/wheel_front_centered.stl"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>

    <collision name="wheel_front_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.8</mu>
            <mu2>1.8</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1e7</kp>
            <kd>1e5</kd>
          </ode>
        </contact>
      </surface>
    </collision>

    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="front_wheel_joint" type="continuous">
    <parent link="steering_link"/>
    <child  link="wheel_front_link"/>
    <origin xyz="-0.051 0.005 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.001" friction="0.0"/>
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <!-- ===== Decorative / extra links ===== -->
  <link name="wheel_front_frame_link">
    <visual>
      <origin xyz="0 -0.13 -0.05"/>
      <geometry>
        <mesh filename="${mesh_path}/wheel_front_frame.stl"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <inertial>
      <mass value="${frame_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="wheel_front_frame_joint" type="fixed">
    <parent link="steering_link"/>
    <child  link="wheel_front_frame_link"/>
    <origin xyz="-0.12 0.175 -0.0258"/>
  </joint>

  <link name="pillar_link">
    <visual>
      <origin xyz="0 0 0.12"/>
      <geometry>
        <mesh filename="${mesh_path}/pillar.stl"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>
    <inertial>
      <mass value="${pillar_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="pillar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="pillar_link"/>
    <origin xyz="0 0 0.12"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0.02"/>
      <geometry>
        <mesh filename="${mesh_path}/lidar.stl"/>
      </geometry>
      <material name="red">
        <color rgba="0.9 0.1 0.1 1"/>
      </material>
    </visual>
    <inertial>
      <mass value="${lidar_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="pillar_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0 0 0.1"/>
  </joint>

  <link name="omron_link">
    <visual>
      <origin xyz="-0.05 0 -0.08"/>
      <geometry>
        <mesh filename="${mesh_path}/omron.stl"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.1 0.9 1"/>
      </material>
    </visual>
    <inertial>
      <mass value="${omron_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="omron_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="omron_link"/>
    <origin xyz="0.05 0 0.08"/>
  </joint>

  <!-- ===== ros2_control ===== -->
  <ros2_control name="AntbotSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
      <!-- เพิ่มเกนให้ขึ้นรอบไวขึ้น -->
      <param name="velocity_proportional_gain">350.0</param>
      <param name="position_proportional_gain">30.0</param>
    </hardware>

    <joint name="wheel_rear_left_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="wheel_rear_right_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="front_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- ===== Gazebo extensions ===== -->
  <gazebo reference="base_link">
    <gravity>1</gravity>
    <self_collide>0</self_collide>
  </gazebo>
  <gazebo reference="wheel_front_link">
    <gravity>1</gravity>
    <self_collide>0</self_collide>
  </gazebo>
  <gazebo reference="wheel_rear_left_link">
    <gravity>1</gravity>
    <self_collide>0</self_collide>
  </gazebo>
  <gazebo reference="wheel_rear_right_link">
    <gravity>1</gravity>
    <self_collide>0</self_collide>
  </gazebo>

  <!-- ros2_control plugin params (ชี้ไฟล์คอนฟิกคอนโทรลเลอร์) -->
  <gazebo>
    <plugin
      filename="libgz_ros2_control-system.so"
      name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <!-- ใช้ $(find ...) ที่ xacro รองรับ -->
      <parameters>$(find antbot_drive_controller)/config/tricycle_controller.yaml</parameters>
    </plugin>
  </gazebo>

</robot>
