<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="antbot">

  <!-- Includes -->
   <!-- รวมมาโคร LiDAR -->
  <xacro:include filename="$(find antbot_description)/urdf/sensors/antbot_lidar.xacro"/>
  <!-- รวมมาโคร IMU -->
  <xacro:include filename="$(find antbot_description)/urdf/sensors/antbot_imu.xacro"/>
   <!-- ✅ รวมมาโคร Ultrasonic -->
  <xacro:include filename="$(find antbot_description)/urdf/sensors/antbot_ultrasonic.xacro"/>

  <!-- ===== Params ===== -->
  <xacro:arg name="ctrl_yaml" default=""/>

  <xacro:property name="base_clearance" value="0.03"/>
  <xacro:property name="mesh_path"    value="package://antbot_description/meshes"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width"  value="0.06"/>

  <xacro:property name="base_size_x" value="0.55"/>
  <xacro:property name="base_size_y" value="0.42"/>
  <xacro:property name="base_size_z" value="0.10"/>

  <xacro:property name="base_mass"   value="5.0"/>
  <xacro:property name="wheel_mass"  value="1.0"/>
  <xacro:property name="frame_mass"  value="0.10"/>
  <xacro:property name="pillar_mass" value="0.20"/>
  <xacro:property name="lidar_mass"  value="0.10"/>
  <xacro:property name="omron_mass"  value="0.10"/>
  <xacro:property name="steer_mass"  value="0.05"/>

  <!-- จุดติดตั้งหัว LiDAR -->
  <xacro:property name="lidar_x" value="-0.013"/>
  <xacro:property name="lidar_y" value="0.063"/>
  <xacro:property name="lidar_z" value="0.613"/>

  <!-- ===== inertia helpers ===== -->
  <xacro:macro name="inertial_box" params="mass x y z ox oy oz">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="${ox} ${oy} ${oz}"/>
      <inertia
        ixx="${mass*(y*y + z*z)/12.0}" ixy="0" ixz="0"
        iyy="${mass*(x*x + z*z)/12.0}" iyz="0"
        izz="${mass*(x*x + y*y)/12.0}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cyl_x" params="mass r l">
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0"/>
      <inertia
        ixx="${0.5*mass*r*r}" ixy="0" ixz="0"
        iyy="${mass*(3*r*r + l*l)/12.0}" iyz="0"
        izz="${mass*(3*r*r + l*l)/12.0}"/>
    </inertial>
  </xacro:macro>

  <!-- ===== Base ===== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 1.57079632679"/>
      <geometry><mesh filename="${mesh_path}/antbot_base1.stl"/></geometry>
      <material name="gray"><color rgba="0.6 0.6 0.6 1"/></material>
    </visual>

    <collision name="base_link_collision">
      <origin xyz="0 0 ${base_size_z/2.0 + base_clearance}" rpy="0 0 0"/>
      <geometry><box size="${base_size_x} ${base_size_y} ${base_size_z}"/></geometry>
      <surface><friction><ode><mu>0.3</mu><mu2>0.3</mu2></ode></friction></surface>
    </collision>

    <xacro:inertial_box mass="${base_mass}"
      x="${base_size_x}" y="${base_size_y}" z="${base_size_z}"
      ox="0" oy="0" oz="${base_size_z/2.0 + base_clearance}"/>
  </link>

   <!-- จุดฉายลงพื้น: roll/pitch = 0 -->
  <link name="base_footprint"/>

  <!-- ยก base_link ลอยจากพื้นด้วย base_clearance (เช่น 0.03 m) -->
  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <!-- ถ้ามี property base_clearance อยู่แล้ว ใช้เลย -->
    <origin xyz="0 0 ${base_clearance}" rpy="0 0 0"/>
  </joint>

  <!-- ===== ติดตั้ง IMU ให้ลอยเหนือฐานเล็กน้อย ===== -->
  <xacro:antbot_imu
    parent="base_link"
    frame_id="imu_link"
    xyz_offset="0.45 0 0.959"
    rpy_offset="0 0 0"
    update_rate="100.0"/>
  <!-- ===== Wheels ===== -->
  <link name="wheel_rear_left_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><mesh filename="${mesh_path}/wheel_rear_centered_clean.stl"/></geometry>
      <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
    </visual>
    <collision name="wheel_rear_left_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <surface>
        <friction><ode><mu>1.8</mu><mu2>1.8</mu2></ode></friction>
        <contact><ode><kp>1e7</kp><kd>1e5</kd></ode></contact>
      </surface>
    </collision>
    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="wheel_rear_left_joint" type="continuous">
    <parent link="base_link"/><child link="wheel_rear_left_link"/>
    <origin xyz="-0.0025 0.29 ${wheel_radius}" rpy="0 0 1.57079632679"/>
    <axis xyz="1 0 0"/><dynamics damping="0.001" friction="0.0"/>
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <link name="wheel_rear_right_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><mesh filename="${mesh_path}/wheel_rear_centered_clean.stl"/></geometry>
      <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
    </visual>
    <collision name="wheel_rear_right_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <surface>
        <friction><ode><mu>1.8</mu><mu2>1.8</mu2></ode></friction>
        <contact><ode><kp>1e7</kp><kd>1e5</kd></ode></contact>
      </surface>
    </collision>
    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="wheel_rear_right_joint" type="continuous">
    <parent link="base_link"/><child link="wheel_rear_right_link"/>
    <origin xyz="-0.0025 -0.23 ${wheel_radius}" rpy="0 0 1.57079632679"/>
    <axis xyz="1 0 0"/><dynamics damping="0.001" friction="0.0"/>
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <!-- ===== Steering + front wheel ===== -->
  <link name="steering_link">
    <inertial>
      <mass value="${steer_mass}"/><origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="steering_joint" type="revolute">
    <parent link="base_link"/><child link="steering_link"/>
    <origin xyz="0.53 0.0025 ${wheel_radius}" rpy="0 0 1.57079632679"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="2.0" friction="0.0"/> 
    <limit effort="8.0" velocity="1.8" lower="-0.62" upper="0.62"/>
  </joint>

  <link name="wheel_front_link">
    <visual>
      <origin xyz="0.028 0 0"/>
      <geometry><mesh filename="${mesh_path}/wheel_front_centered.stl"/></geometry>
      <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
    </visual>
    <collision name="wheel_front_link_collision">
      <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <surface>
        <friction><ode><mu>1.8</mu><mu2>1.8</mu2></ode></friction>
        <contact><ode><kp>1e7</kp><kd>1e5</kd></ode></contact>
      </surface>
    </collision>
    <xacro:inertial_cyl_x mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
  </link>

  <joint name="front_wheel_joint" type="continuous">
    <parent link="steering_link"/><child link="wheel_front_link"/>
    <origin xyz="0 0.005 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/><dynamics damping="0.001" friction="0.0"/>
    <limit effort="80.0" velocity="120.0"/>
  </joint>

  <!-- ===== Extra visuals ===== -->
  <link name="wheel_front_frame_link">
    <visual>
      <origin xyz="0 -0.13 -0.05"/>
      <geometry><mesh filename="${mesh_path}/wheel_front_frame3.stl"/></geometry>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <inertial>
      <mass value="${frame_mass}"/><origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="wheel_front_frame_joint" type="fixed">
    <parent link="steering_link"/><child link="wheel_front_frame_link"/>
    <origin xyz="0 0.175 -0.0258"/>
  </joint>

  <!-- ===== Pillar ===== -->
  <link name="pillar_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><mesh filename="${mesh_path}/pillar_centered_origin.stl"/></geometry>
      <material name="gray"><color rgba="0.6 0.6 0.6 1"/></material>
    </visual>
    <inertial>
      <mass value="${pillar_mass}"/><origin xyz="0 0 0"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="pillar_joint" type="fixed">
    <parent link="base_link"/><child link="pillar_link"/>
    <origin xyz="0.0015 0.025 1.1917" rpy="0 0 1.57079632679"/>
  </joint>

  <!-- ===== LiDAR head ===== -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0.02"/>
      <geometry><mesh filename="${mesh_path}/lidar_centered_origin.stl"/></geometry>
      <material name="red"><color rgba="0.9 0.1 0.1 1"/></material>
    </visual>
    <inertial>
      <mass value="${lidar_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="pillar_link"/><child link="lidar_link"/>
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- กรอบเซนเซอร์ LiDAR -->
  <link name="lidar_sensor_link"/>
  <joint name="lidar_sensor_joint" type="fixed">
    <parent link="lidar_link"/>
    <child  link="lidar_sensor_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ผูกปลั๊กอิน LiDAR -->
  <xacro:antbot_lidar_attach
    link="lidar_sensor_link"
    topic="/scan_raw"
    frame_id="lidar_sensor_link"
    update_rate="15"
    visualize="true"
    samples="720"       
    resolution="1"
    min_angle="-3.14159"
    max_angle="3.14159"
    vertical_samples="1"
    vertical_resolution="1"
    vertical_min_angle="0"
    vertical_max_angle="0"
    range_min="0.15"
    range_max="8.0"
    noise_stddev="0.003"/>

  <!-- ===== Ultrasonic (หน้ากลาง) ===== -->
  <xacro:antbot_ultrasonic
    parent="base_link"
    frame="ultrasonic_front_link"
    joint_xyz_offset="0.85 0.02 0.55"
    joint_rpy_offset="0 0 1.57079632679"
    rpy_offset="0 0 0"               
    min_range="0.25"
    max_range="4.0"
    update_rate="10"
    visualize="true"
    min_angle="-0.12"
    max_angle="0.12"
    topic="/ultrasonic"/>

  <!-- ===== Omron link ===== -->
  <link name="omron_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry><mesh filename="${mesh_path}/omron_fixed.stl"/></geometry>
      <material name="blue"><color rgba="0.1 0.1 0.9 1"/></material>
    </visual>
    <inertial>
      <mass value="${omron_mass}"/><origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="omron_joint" type="fixed">
    <parent link="base_link"/><child link="omron_link"/>
    <origin xyz="0.83 0.020 0.86234" rpy="0 0 1.57079632679" />
  </joint>

  <!-- ===== ros2_control ===== -->
  <ros2_control name="AntbotSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
      <param name="velocity_proportional_gain">350.0</param>
      <param name="position_proportional_gain">30.0</param>
    </hardware>

    <joint name="wheel_rear_left_joint"><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="wheel_rear_right_joint"><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="front_wheel_joint"><command_interface name="velocity"/><state_interface name="position"/><state_interface name="velocity"/></joint>
    <joint name="steering_joint"><command_interface name="position"/><state_interface name="position"/><state_interface name="velocity"/></joint>
  </ros2_control>

  <!-- ===== Gazebo tags ===== -->
  <gazebo reference="base_link"><gravity>1</gravity><self_collide>0</self_collide></gazebo>
  <gazebo reference="wheel_front_link"><gravity>1</gravity><self_collide>0</self_collide></gazebo>
  <gazebo reference="wheel_rear_left_link"><gravity>1</gravity><self_collide>0</self_collide></gazebo>
  <gazebo reference="wheel_rear_right_link"><gravity>1</gravity><self_collide>0</self_collide></gazebo>

  <!-- ros2_control plugin -->
  <gazebo>
    <plugin filename="libgz_ros2_control-system.so"
          name="gz_ros2_control::GazeboSimROS2ControlPlugin">
    <!-- เดิม: <parameters>${ctrl_yaml}</parameters> -->
      <parameters>$(arg ctrl_yaml)</parameters>
    </plugin>
  </gazebo>
  <!-- IMU plugin -->
  <gazebo>
    <plugin filename="libgz-sim-imu-system.so" name="gz::sim::systems::Imu">
      <entity_name>imu_link</entity_name>
      <entity_type>link</entity_type>
      <topic>imu</topic>
      <frame_id>imu_link</frame_id>
      <update_rate>100</update_rate>
    </plugin>
  </gazebo>


</robot>